# fly.toml app configuration file generated for esohasl-api on 2024-08-03T22:40:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'esohasl-api'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 3
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 250
    hard_limit = 750
  [[http_service.checks]]
    grace_period = "10s"
    interval = "10s"
    method = "GET"
    timeout = "5s"
    path = "/ping"

[env]
  AUTH_DOMAIN = "esohasl.net"
  HOME_URL = "https://esohasl.net"

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256
